| model | auc | C |
|:---:|:---:|:---:|
| lgbv5 | 0.9850713071685091 | 1e6 |
| lgbv5 + lgb1 | 0.9851092945152703 | 1e6 |
| lgbv5 + wbftl | 0.9855448213140752 | 1e6 |
| lgbv5 + nngpu | 0.9851237957968813 | 1e6 |
| lgbv5 + kernellgb | 0.9851271472858812 | 1e6 |
| lgbv5 + myxgb | 0.9854292800622805 | 1e6 |
| lgbv5 + callum-lgb | 0.9855025065682748 | 1 |
| lgbv5 + simple-lgb | 0.9852361704355532 | 1e6 |
| lgbv5 + simple-xgb | 0.9856731359175543 | 1 |
| lgbv5 + md_lgb | 0.9853367372901444 | 1 |
| lgbv5 + simple-xgb + lgb1 | 0.9855276062692947 | 1e6 |
| lgbv5 + simple-xgb + wbftl | 0.9858510654437075 | 1e6 |
| lgbv5 + simple-xgb + nngpu | 0.9855309185495338 | 1e6 |
| lgbv5 + simple-xgb + kernellgb | 0.9856510088819995 | 1e6 |
| lgbv5 + simple-xgb + myxgb | 0.9856149459800625 | 1e6 |
| lgbv5 + simple-xgb + callum-lgb | 0.985793653522653 | 1 |
| lgbv5 + simple-xgb + simple-lgb | 0.9855496363634353 | 1e6 |
| lgbv5 + simple-xgb + md_lgb | 0.9857526139173335 | 1 |
| lgbv5 + simple-xgb + wbftl + lgb1 | 0.9856550880280361 | 1e6 |
| lgbv5 + simple-xgb + wbftl + nngpu | 0.9857184593523003 | 1e6 |
| lgbv5 + simple-xgb + wbftl + kernellgb | 0.9858392825108588 | 1e6 |
| lgbv5 + simple-xgb + wbftl + myxgb | 0.9858087815696206 | 1e6 |
| lgbv5 + simple-xgb + wbftl + callum-lgb | 0.9858883060087889 | 1e6 |
| lgbv5 + simple-xgb + wbftl + simple-lgb | 0.9858097397985477 | 1e6 |
| lgbv5 + simple-xgb + wbftl + md_lgb | 0.9858892786384648 | 1e6 |
| lgbv5 + simple-xgb + wbftl + md_lgb + callum-lgb | 0.9859145972507446 | 1e6 |
| lgbv5 + simple-xgb + wbftl + callum-lgb + md_xgb | 0.9859604408541893 | 1e6 |
| lgbv5 + simple-xgb + wbftl + md_lgb + callum-lgb + md_xgb | 0.9859635209072296 | 1 |

In [4]:
"""model_order = [m for m in base_models] 

cvdata2 = pd.DataFrame( { 
    m:pd.read_csv(subfiles[m])['is_attributed'].rank()
    for m in base_models
    } )
X_train2 = np.array(cvdata2[model_order])
y_train2 = pd.read_csv(TEST_FILE)['is_attributed']
y_train2 = round(y_train2).astype(np.int8)
n = len(y_train2)
X_train2 /= n

X_train = np.vstack((X_train, X_train2))
y_train = np.concatenate((y_train, y_train2))"""

In [2]:
import numpy as np
import pandas as pd
import os
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

In [15]:
almost_zero = 1e-10
almost_one = 1 - almost_zero
VAL_FILE = './data/validation.pkl.gz'
TEST_FILE = "./data/sub_stacked.csv"

base_models = {
    #'lgb1 ': "assemblage of krishna's LGBM with time deltas",
    'wbftl': "anttip's Wordbatch FM-FTRL",
    #'nngpu': "Downampled Neural Network run on GPU",
    #"kernellgb": "kernellgb",
    #"myxgb": "myxgb",
    #"callum-lgb": "callum-lgb",
    #"simple-lgb": "simple-lgb",
    #"simple-xgb": "simple-xgb",
    "lgbv5": "lgbv5",
    #"md_lgb": "md_lgb",
    #"md_xgb": "md_xgb",
    }

cvfiles = {
    #'lgb1 ': './val/val_krishnas_r_lgb_bag3.csv',
    'wbftl': './val/wordbatch_fm_ftrl_val.csv',
    #'nngpu': './val/gpu_val3.csv',
    #"kernellgb": "./val/kernellgb_val.csv.gz",
    #"myxgb": "val/my_xgbval.csv.gz",
    #"callum-lgb": "val/callum-lgbval.csv.gz",
    #"simple-lgb": "val/simple_lgbm2_val.csv.gz",
    #"simple-xgb": "val/simple_xgb_val.csv.gz",
    "lgbv5": "solution5/lgbv8val.csv.gz",
    #"md_lgb": "val/md_val.csv.gz",
    #"md_xgb": "val/mdxgb_val.csv.gz",
    }

subfiles = {
    #'lgb1 ': './pred/sub_krishnas_r_lgb_bag4.csv',
    'wbftl': './result/wordbatch_fm_ftrl.csv',
    #'nngpu': './pred/gpu_test3.csv',
    #"kernellgb": "./pred/kernellgb.csv.gz",
    #"myxgb": "./pred/my_xgbsub.csv.gz",
    #"callum-lgb": "./pred/callum-lgbsub.csv.gz",
    #"simple-lgb": "pred/simple_lgbm2.csv.gz",
    #"simple-xgb": "pred/simple_xgb.csv.gz",
    "lgbv5": "result/lgbv8sub.csv.gz",
    #"md_lgb": "pred/md_sub.csv.gz",
    #"md_xgb": "pred/mdxgb_sub.csv.gz",
    }

lbscores = {
    #'lgb1 ': .9759,
    'wbftl': .9752,
    #'nngpu': .9695,
    #"kernellgb": .9786,
    #"myxgb": .9778,
    #"callum-lgb": .9790,
    #"simple-lgb": .9779,
    #"simple-xgb": .9785,
    "lgbv5": .9798,
    #"md_lgb": .9795,
    #"md_xgb": .9786,
}

In [16]:
model_order = [m for m in base_models] 

cvdata = pd.DataFrame( { 
    m:pd.read_csv(cvfiles[m])['is_attributed'].rank()
    for m in base_models
    } )
X_train = np.array(cvdata[model_order])
y_train = pd.read_pickle(VAL_FILE)['is_attributed']
n = len(y_train)
X_train /= n

In [17]:
X, X_val, y, y_val = train_test_split(X_train, y_train, test_size=.33, shuffle=False )
#for c in [1, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6]:
for c in [1e6]:
    mod = LogisticRegression(C=c)
    mod.fit(X, y)
    val_pred = mod.predict_proba(X_val)[:,1]
    print( c, roc_auc_score(y_val, mod.predict_proba(X_val)[:,1]) )

1000000.0 0.9855370056232459

In [30]:
stack_model = LogisticRegression(C=1e6)
stack_model.fit(X_train, y_train)
stack_model.coef_

array([[15.40876305,  6.02290716,  7.87265948, 10.06270015,  8.45820873]])

In [26]:
weights = stack_model.coef_/stack_model.coef_.sum()
columns = cvdata[model_order].columns
#scores = [ roc_auc_score( y_train, cvdata[c] )  for c in columns ]
names = [ base_models[c] for c in columns ]
lb = [ lbscores[c] for c in columns ]
pd.DataFrame( data={'LB score': lb,
                    #'CV score':scores,
                    'weight':weights.reshape(-1)}, index=names )

                             LB score     weight
anttip's Wordbatch FM-FTRL 0.97520000 0.31911853
callum-lgb                 0.97900000 0.09618230
simple-xgb                 0.97850000 0.15090245
lgbv5                      0.97970000 0.15096670
md_xgb                     0.97860000 0.20201681
bi_lgb                     0.97600000 0.08081321

In [7]:
print('Stacker score: ', roc_auc_score(y_train, stack_model.predict_proba(X_train)[:,1]))

Stacker score:  0.9809504733773653

In [8]:
final_sub = pd.DataFrame()
subs = {m:pd.read_csv(subfiles[m]).rename({'is_attributed':m},axis=1) for m in base_models}
first_model = list(base_models.keys())[0]
final_sub['click_id'] = subs[first_model]['click_id']

In [9]:
df = subs[first_model]
for m in subs:
    if m != first_model:
        df = df.merge(subs[m], on='click_id')  # being careful in case clicks are in different order
df.head()

   click_id     wbftl  callum-lgb  simple-xgb     lgbv5    md_lgb    md_xgb
0         0  0.002104    0.069337    0.367091  0.152173  0.119230  0.239588
1         1  0.001093    0.010899    0.026598  0.018905  0.024401  0.041623
2         2  0.000104    0.001120    0.005705  0.002625  0.001794  0.012788
3         3  0.000689    0.010233    0.040021  0.030479  0.034965  0.081681
4         4  0.000504    0.006949    0.039511  0.023245  0.015851  0.064384

In [10]:
X_test = np.array( df.drop(['click_id'],axis=1)[model_order].rank()/df.shape[0] )
final_sub['is_attributed'] = stack_model.predict_proba(X_test)[:,1]
final_sub.head(10)

   click_id  is_attributed
0         0   1.397962e-05
1         1   4.747517e-12
2         2   3.272474e-18
3         3   2.746380e-11
4         4   3.663667e-12
5         5   5.229495e-15
6         6   1.365244e-09
7         7   2.230755e-05
8         9   8.095550e-05
9         8   6.721629e-16

In [11]:
final_sub['is_attributed'] = final_sub['is_attributed'].rank(method='dense') / 1e8
pd.options.display.float_format = ('{:,.8f}').format
final_sub.head(10)

   click_id  is_attributed
0         0     0.15635176
1         1     0.09258787
2         2     0.03122431
3         3     0.10022484
4         4     0.09145792
5         5     0.06287577
6         6     0.11730115
7         7     0.15825764
8         9     0.16336947
9         8     0.05397576

In [11]:
#final_sub[df.duplicated(["ip", "app", "device", "os", "channel", "click_time"], keep=False)]

ValueError: not enough values to unpack (expected 2, got 0)

In [25]:
#df = pd.read_csv("data/test.csv")
#final_sub["is_attributed"] = np.where(df.duplicated(["ip", "app", "device", "os", "channel", "click_time"], keep="last"),
#                                      0.01, final_sub["is_attributed"])

In [26]:
#final_sub[df.duplicated(["ip", "app", "device", "os", "channel", "click_time"], keep=False)]

          click_id  is_attributed
15              15     0.01000000
17              20     0.01724369
20              18     0.01000000
58              58     0.01000000
61              61     0.07423414
162            162     0.01000000
166            166     0.10655760
232            232     0.00068545
451            451     0.01000000
453            453     0.01000000
457            457     0.01484809
515            517     0.01000000
521            521     0.01000000
522            522     0.06482361
537            537     0.01000000
560            560     0.01000000
625            625     0.02461912
801            801     0.01000000
803            804     0.01000000
856            856     0.01000000
863            863     0.01000000
871            871     0.01625222
891            891     0.01000000
935            935     0.04461275
939            939     0.09176747
979            979     0.10716226
1089          1089     0.15362471
1143          1143     0.00679334
1157          1157     0.18147114
1214          1214     0.15580331
...            ...            ...
18789596  18789596     0.01000000
18789612  18789612     0.01000000
18789627  18789627     0.06231328
18789653  18789653     0.16535987
18789666  18789666     0.01000000
18789687  18789687     0.13858230
18789690  18789689     0.06826571
18789698  18789698     0.01000000
18789702  18789702     0.15647743
18789707  18789707     0.18216750
18789729  18789728     0.02855742
18789769  18789769     0.02915488
18789803  18789803     0.14811419
18789809  18789809     0.02437086
18789817  18789818     0.14269815
18789841  18789841     0.03789717
18789848  18789848     0.01381386
18789922  18789922     0.14797334
18789977  18789977     0.01000000
18790015  18790015     0.03994905
18790204  18790204     0.01000000
18790208  18790209     0.01000000
18790263  18790263     0.03386000
18790272  18790272     0.15532270
18790353  18790355     0.01000000
18790375  18790375     0.14657583
18790436  18790436     0.01000000
18790437  18790437     0.01081392
18790438  18790439     0.01000000
18790466  18790467     0.12375414

[606424 rows x 2 columns]

In [12]:
final_sub.to_csv("sub_stacked.csv", index=False, float_format='%.8f')

In [16]:
df = pd.read_csv("sub_stacked.csv")
pr = final_sub['is_attributed'].values + (final_sub['is_attributed'].values - df['is_attributed'].values)*0.01

In [17]:
pr[:5]

array([0.15628718, 0.09259394, 0.03132222, 0.10026317, 0.09160678])

In [18]:
final_sub['is_attributed'] = pr
final_sub.to_csv("sub_stacked.csv", index=False, float_format='%.8f')